version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    depends_on:
      - mariadb
      - redis
    volumes:
      - .:/var/www/html:rw
    ports:
      - 80:8080

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      MARIADB_ROOT_PASSWORD: secret
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6

  adminer:
    image: adminer
    depends_on:
      - mariadb
    ports:
      - 8080:8080

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
  mariadb_data:
    driver: local
